resources:
  - url: http://127.0.0.1:5000/countdown-timer-card.js
    type: module
views:
  - cards:
      - type: custom:countdown-timer-card
        name: Countdown Timer Card Development
        entity: sun.sun
        test_gui: true
